<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="inertia_eqs.xacro"/>

    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>

    <material name="green">
        <color rgba="0.3 1 0.3 1"/>
    </material>

    <material name="grey">
        <color rgba="0.78 0.61 0.77 1"/>
    </material>

    <!--Base Link-->
    <link name="base_link"></link>

    <xacro:property name="width" value="0.5"/>
    <xacro:property name="length" value="0.5"/>
    <xacro:property name="height" value="0.25"/>
    <xacro:property name="wheel_radius" value="0.1"/>
    <xacro:property name="wheel_length" value="0.05"/>

    <!--CHASSIS-->
    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="-${length/4} 0.0 0.0"/>
    </joint>

    <link name="chassis">
        <visual>
            <origin xyz="${length/2} 0 ${height/2}"/>
            <geometry>
                <box size="${length} ${width} ${height}"   /> 
            </geometry>
            <material name="green"/>
        </visual>
        <collision>
            <origin xyz="${length/2} 0 ${height/2}"/>
            <geometry>
                <box size="${length} ${width} ${height}"   /> 
            </geometry>
            <material name="green"/>
        </collision>
        <xacro:inertial_box mass="1" x="${length}" y="${width}" z="${height}">
            <origin xyz="${length/2} 0 ${height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="chassis">
        <material>Gazebo/Green</material>
    </gazebo>
        
    <!--LEFT WHEEL-->
    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
        <origin xyz="0 ${width/2 + wheel_length/2} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="grey"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="left_wheel">
        <material>Gazebo/Grey</material>
    </gazebo>

    <!--RIGHT WHEEL-->
    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
        <origin xyz="0 -${width/2 + wheel_length/2} 0" rpy="-${pi/2} 0 0" />
        <axis xyz="0 0 1"/>
    </joint>

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="grey"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <gazebo reference="right_wheel">
        <material>Gazebo/Grey</material>
    </gazebo>

    <!--CASTER-->
    <joint name="caster_wheel_joint" type="fixed">
        <parent link="base_link"/>
        <child link="caster_wheel"/>
        <origin xyz="${length/2} 0 0"/>
    </joint>


    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="0.1" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel">
        <material>Gazebo/White</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>

    
    
</robot>